# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

t1 =  Team.create(shortname: 'ARS', fullname: 'Arsenal', yearfounded: 1886, budget: 100000000)
t2 =  Team.create(shortname: 'EVE', fullname: 'Everton', yearfounded: 1878, budget: 105060200)
t3 =  Team.create(shortname: 'AFCB', fullname: 'AFC Bournemouth', yearfounded: 1899, budget: 0)
t4 =  Team.create(shortname: 'BHA', fullname: 'Brighton and Hove Albion', yearfounded: 1901, budget: 0)
t5 =  Team.create(shortname: 'BFC', fullname: 'Burnley', yearfounded: 1882, budget: 0)
t6 =  Team.create(shortname: 'CAR', fullname: 'Cardiff City', yearfounded: 1899, budget: 0)
t7 =  Team.create(shortname: 'CFC', fullname: 'Chelsea', yearfounded: 1905, budget: 0)
t8 =  Team.create(shortname: 'CPFC', fullname: 'Crystal Palace', yearfounded: 1905, budget: 0)
t9 =  Team.create(shortname: 'FUL', fullname: 'Fulham', yearfounded: 1879, budget: 0)
t10 = Team.create(shortname: 'HUD', fullname: 'Huddersfield Town', yearfounded: 1884, budget: 0)
t11 = Team.create(shortname: 'LEI', fullname: 'Leicester City', yearfounded: 1884, budget: 0)
t12 = Team.create(shortname: 'LIV', fullname: 'Liverpool', yearfounded: 1892, budget: 0)
t13 = Team.create(shortname: 'MCI', fullname: 'Manchester City', yearfounded: 1880, budget: 0)
t14 = Team.create(shortname: 'MUN', fullname: 'Manchester United', yearfounded: 1878, budget: 0)
t15 = Team.create(shortname: 'NEW', fullname: 'Newcastle United', yearfounded: 1892, budget: 0)
t16 = Team.create(shortname: 'SOU', fullname: 'Southampton', yearfounded: 1885, budget: 0)
t17 = Team.create(shortname: 'TOT', fullname: 'Tottenhan Hotspur', yearfounded: 1882, budget: 0)
t18 = Team.create(shortname: 'WAT', fullname: 'Watford', yearfounded: 1898, budget: 0)
t19 = Team.create(shortname: 'WHU', fullname: 'West Ham United', yearfounded: 1895, budget: 0)
t20 = Team.create(shortname: 'WQL', fullname: 'Wolverhampton Wanderers', yearfounded: 1877, budget: 0)

#   Players Creation
t1.players.create(firstname: 'Petr', lastname: 'Cech', nationality: 'Czech Republic', position: 'Goalkeeper', yearsofexperience: '4', salary: '100000') 
t1.players.create(firstname: 'Bernd', lastname: 'Leno', nationality: 'Germany', position: 'Goalkeeper', yearsofexperience: '2', salary: '10000') 
t1.players.create(firstname: 'Hector', lastname: 'Bellerin', nationality: 'Spain', position: 'Defender', yearsofexperience: '1', salary: '50000') 
t1.players.create(firstname: 'Igor', lastname: 'Sokratis', nationality: 'Greece', position: 'Defender', yearsofexperience: '3', salary: '150000') 
t1.players.create(firstname: 'Laurent', lastname: 'Koscielny', nationality: 'France', position: 'Defender', yearsofexperience: '2', salary: '20000') 
t1.players.create(firstname: 'Stephan', lastname: 'Lichtsteiner', nationality: 'Switzerland', position: 'Defender', yearsofexperience: '6', salary: '350000') 
t1.players.create(firstname: 'Mohamed', lastname: 'Elneny', nationality: 'Egypt', position: 'Midfielder', yearsofexperience: '4', salary: '350000') 
t1.players.create(firstname: 'Henrikh', lastname: 'Mkhitaryan', nationality: 'Armenia', position: 'Midfielder', yearsofexperience: '4', salary: '60000') 
t1.players.create(firstname: 'Aaron', lastname: 'Ramsey', nationality: 'Wales', position: 'Midfielder', yearsofexperience: '7', salary: '850000') 
t1.players.create(firstname: 'Mesut', lastname: 'Ozil', nationality: 'Germany', position: 'Midfielder', yearsofexperience: '3', salary: '350000') 
t1.players.create(firstname: 'Alexandre', lastname: 'Lacazette', nationality: 'France', position: 'Forward', yearsofexperience: '3', salary: '150000') 
t1.players.create(firstname: 'Pierre-Emerick', lastname: 'Aubameyang', nationality: 'Gabon', position: 'Forward', yearsofexperience: '2', salary: '150000') 
t1.players.create(firstname: 'Alex', lastname: 'Iwobi', nationality: 'Nigeria', position: 'Forward', yearsofexperience: '1', salary: '100000') 
t1.players.create(firstname: 'Danny', lastname: 'Welbeck', nationality: 'England', position: 'Forward', yearsofexperience: '3', salary: '230000') 
t1.players.create(firstname: 'Takuma', lastname: 'Asano', nationality: 'Japan', position: 'On Loan', yearsofexperience: '1', salary: '10000') 

t2.players.create(firstname: 'Jordan', lastname: 'Pickford', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '3', salary: '750000') 
t2.players.create(firstname: 'Maarten', lastname: 'Stekelenburg', nationality: 'Netherlands', position: 'Goalkeeper', yearsofexperience: '0', salary: '50000') 
t2.players.create(firstname: 'Leighton', lastname: 'Baines', nationality: 'England', position: 'Defender', yearsofexperience: '1', salary: '150000') 
t2.players.create(firstname: 'Michael', lastname: 'Keane', nationality: 'England', position: 'Defender', yearsofexperience: '4', salary: '490000') 
t2.players.create(firstname: 'Phil', lastname: 'Jagielka', nationality: 'England', position: 'Defender', yearsofexperience: '1', salary: '190000') 
t2.players.create(firstname: 'Seamus', lastname: 'Coleman', nationality: 'Ireland', position: 'Defender', yearsofexperience: '4', salary: '500000') 
t2.players.create(firstname: 'Morgan', lastname: 'Schneiderlin', nationality: 'France', position: 'Midfielder', yearsofexperience: '2', salary: '200000') 
t2.players.create(firstname: 'James', lastname: 'McCarthy', nationality: 'Ireland', position: 'Midfielder', yearsofexperience: '0', salary: '10000') 
t2.players.create(firstname: 'Idrissa', lastname: 'Gueye', nationality: 'Senegal', position: 'Midfielder', yearsofexperience: '2', salary: '250000') 
t2.players.create(firstname: 'Gylfi', lastname: 'Sigurdsson', nationality: 'Iceland', position: 'Midfielder', yearsofexperience: '5', salary: '850000') 
t2.players.create(firstname: 'Theo', lastname: 'Walcott', nationality: 'England', position: 'Forward', yearsofexperience: '5', salary: '900000') 
t2.players.create(firstname: 'Cenk', lastname: 'Tosun', nationality: 'Turkey', position: 'Forward', yearsofexperience: '4', salary: '300000') 
t2.players.create(firstname: 'Dominic', lastname: 'Calvert-Lewin', nationality: 'England', position: 'Forward', yearsofexperience: '6', salary: '900000') 
t2.players.create(firstname: 'Ademola', lastname: 'Lookman', nationality: 'England', position: 'Forward', yearsofexperience: '3', salary: '230000') 

t3.players.create(firstname: 'Artur', lastname: 'Boruc', nationality: 'Poland', position: 'Goalkeeper', yearsofexperience: '3', salary: '750000') 
t3.players.create(firstname: 'Asmir', lastname: 'Begovic', nationality: 'Boznia And Herzegovina', position: 'Goalkeeper', yearsofexperience: '2', salary: '50000') 
t3.players.create(firstname: 'Simon', lastname: 'Francis', nationality: 'England', position: 'Defender', yearsofexperience: '2', salary: '150000') 
t3.players.create(firstname: 'Steve', lastname: 'Cook', nationality: 'England', position: 'Defender', yearsofexperience: '4', salary: '490000') 
t3.players.create(firstname: 'Nathan', lastname: 'Ake', nationality: 'Netherlands', position: 'Defender', yearsofexperience: '4', salary: '190000') 
t3.players.create(firstname: 'Charlie', lastname: 'Daniels', nationality: 'England', position: 'Defender', yearsofexperience: '6', salary: '500000') 
t3.players.create(firstname: 'Adam', lastname: 'Smith', nationality: 'England', position: 'Midfielder', yearsofexperience: '2', salary: '200000') 
t3.players.create(firstname: 'Dan', lastname: 'Gosling', nationality: 'England', position: 'Midfielder', yearsofexperience: '1', salary: '10000') 
t3.players.create(firstname: 'Andrew', lastname: 'Surman', nationality: 'England', position: 'Midfielder', yearsofexperience: '3', salary: '250000') 
t3.players.create(firstname: 'Lewis', lastname: 'Cook', nationality: 'England', position: 'Midfielder', yearsofexperience: '4', salary: '850000') 
t3.players.create(firstname: 'Callum', lastname: 'Wilson', nationality: 'England', position: 'Forward', yearsofexperience: '5', salary: '900000') 
t3.players.create(firstname: 'Joshua', lastname: 'King', nationality: 'Norway', position: 'Forward', yearsofexperience: '4', salary: '300000') 
t3.players.create(firstname: 'Lys', lastname: 'Mousset', nationality: 'France', position: 'Forward', yearsofexperience: '7', salary: '900000') 
t3.players.create(firstname: 'Dominic', lastname: 'Solanke', nationality: 'England', position: 'Forward', yearsofexperience: '1', salary: '230000') 

t4.players.create(firstname: 'Mat', lastname: 'Ryan', nationality: 'Australia', position: 'Goalkeeper', yearsofexperience: '3', salary: '302000') 
t4.players.create(firstname: 'Jason', lastname: 'Steele', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '1', salary: '150000') 
t4.players.create(firstname: 'David', lastname: 'Button', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '0', salary: '250000') 
t4.players.create(firstname: 'Gaetan', lastname: 'Bong', nationality: 'Cameroon', position: 'Defender', yearsofexperience: '2', salary: '180000') 
t4.players.create(firstname: 'Lewis', lastname: 'Dunk', nationality: 'England', position: 'Defender', yearsofexperience: '3', salary: '390000') 
t4.players.create(firstname: 'Shane', lastname: 'Duffy', nationality: 'Ireland', position: 'Defender', yearsofexperience: '5', salary: '900000') 
t4.players.create(firstname: 'Leon', lastname: 'Balogun', nationality: 'Nigeria', position: 'Defender', yearsofexperience: '4', salary: '520000') 
t4.players.create(firstname: 'Dale', lastname: 'Stephens', nationality: 'England', position: 'Midfielder', yearsofexperience: '1', salary: '140000') 
t4.players.create(firstname: 'Beram', lastname: 'Kayal', nationality: 'Israel', position: 'Midfielder', yearsofexperience: '1', salary: '105000') 
t4.players.create(firstname: 'Anthony', lastname: 'Knockaert', nationality: 'France', position: 'Midfielder', yearsofexperience: '2', salary: '230000') 
t4.players.create(firstname: 'Solly', lastname: 'March', nationality: 'England', position: 'Midfielder', yearsofexperience: '5', salary: '500000') 
t4.players.create(firstname: 'Yves', lastname: 'Bissouma', nationality: 'Mali', position: 'Forward', yearsofexperience: '7', salary: '700000') 
t4.players.create(firstname: 'Will', lastname: 'Collar', nationality: 'England', position: 'Forward', yearsofexperience: '4', salary: '300000') 
t4.players.create(firstname: 'Max', lastname: 'Sanders', nationality: 'England', position: 'Forward', yearsofexperience: '3', salary: '810000') 
t4.players.create(firstname: 'Jayson', lastname: 'Molumby', nationality: 'Ireland', position: 'Forward', yearsofexperience: '2', salary: '220000') 

t5.players.create(firstname: 'Tom', lastname: 'Heaton', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '3', salary: '300000') 
t5.players.create(firstname: 'Anders', lastname: 'Lindegaard', nationality: 'Denmark', position: 'Goalkeeper', yearsofexperience: '5', salary: '510000') 
t5.players.create(firstname: 'Adam', lastname: 'Legzdins', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '2', salary: '250000') 
t5.players.create(firstname: 'Charlie', lastname: 'Taylor', nationality: 'England', position: 'Defender', yearsofexperience: '0', salary: '100000') 
t5.players.create(firstname: 'James', lastname: 'Tarkowski', nationality: 'England', position: 'Defender', yearsofexperience: '3', salary: '490000') 
t5.players.create(firstname: 'Ben', lastname: 'Mee', nationality: 'England', position: 'Defender', yearsofexperience: '9', salary: '990000') 
t5.players.create(firstname: 'Stephen', lastname: 'Ward', nationality: 'Ireland', position: 'Defender', yearsofexperience: '5', salary: '521000') 
t5.players.create(firstname: 'Jack', lastname: 'Cork', nationality: 'England', position: 'Midfielder', yearsofexperience: '2', salary: '200000') 
t5.players.create(firstname: 'Robbie', lastname: 'Brady', nationality: 'Ireland', position: 'Midfielder', yearsofexperience: '2', salary: '355000') 
t5.players.create(firstname: 'Jeff', lastname: 'Hendrick', nationality: 'Ireland', position: 'Midfielder', yearsofexperience: '1', salary: '200000') 
t5.players.create(firstname: 'Steven', lastname: 'Defour', nationality: 'Belgium', position: 'Midfielder', yearsofexperience: '3', salary: '300000') 
t5.players.create(firstname: 'Ashley', lastname: 'Barnes', nationality: 'Austria', position: 'Forward', yearsofexperience: '6', salary: '620000') 
t5.players.create(firstname: 'Chris', lastname: 'Wood', nationality: 'New Zealand', position: 'Forward', yearsofexperience: '2', salary: '150000') 
t5.players.create(firstname: 'Daniel', lastname: 'Agyei', nationality: 'England', position: 'Forward', yearsofexperience: '2', salary: '210000') 
t5.players.create(firstname: 'Matej', lastname: 'Vydra', nationality: 'Czech Republic', position: 'Forward', yearsofexperience: '7', salary: '920000') 

t6.players.create(firstname: 'Neil', lastname: 'Etheridge', nationality: 'Philippines', position: 'Goalkeeper', yearsofexperience: '3', salary: '300000') 
t6.players.create(firstname: 'Alex', lastname: 'Smithies', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '5', salary: '510000') 
t6.players.create(firstname: 'Brain', lastname: 'Murphy', nationality: 'Ireland', position: 'Goalkeeper', yearsofexperience: '2', salary: '250000') 
t6.players.create(firstname: 'Joe', lastname: 'Bennett', nationality: 'England', position: 'Defender', yearsofexperience: '0', salary: '100000') 
t6.players.create(firstname: 'Sean', lastname: 'Morrison', nationality: 'England', position: 'Defender', yearsofexperience: '3', salary: '490000') 
t6.players.create(firstname: 'Bruno Ecuele', lastname: 'Manga', nationality: 'Gabon', position: 'Defender', yearsofexperience: '9', salary: '990000') 
t6.players.create(firstname: 'Jazz', lastname: 'Richards', nationality: 'Wales', position: 'Defender', yearsofexperience: '5', salary: '521000') 
t6.players.create(firstname: 'Joe', lastname: 'Ralls', nationality: 'England', position: 'Midfielder', yearsofexperience: '2', salary: '200000') 
t6.players.create(firstname: 'Kadeem', lastname: 'Harris', nationality: 'England', position: 'Midfielder', yearsofexperience: '2', salary: '355000') 
t6.players.create(firstname: 'Loic', lastname: 'Damour', nationality: 'France', position: 'Midfielder', yearsofexperience: '1', salary: '200000') 
t6.players.create(firstname: 'Josh', lastname: 'Murphy', nationality: 'England', position: 'Midfielder', yearsofexperience: '3', salary: '300000') 
t6.players.create(firstname: 'Danny', lastname: 'Ward', nationality: 'England', position: 'Forward', yearsofexperience: '6', salary: '620000') 
t6.players.create(firstname: 'Kenneth', lastname: 'Zohore', nationality: 'Denmark', position: 'Forward', yearsofexperience: '2', salary: '150000') 
t6.players.create(firstname: 'Nathaniel', lastname: 'Mendez-Laing', nationality: 'England', position: 'Forward', yearsofexperience: '2', salary: '210000') 
t6.players.create(firstname: 'David Junior', lastname: 'Hoilett', nationality: 'Canada', position: 'Forward', yearsofexperience: '7', salary: '920000') 

t7.players.create(firstname: 'Willy', lastname: 'Caballero', nationality: 'Argentina', position: 'Goalkeeper', yearsofexperience: '3', salary: '300000') 
t7.players.create(firstname: 'Robert', lastname: 'Green', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '5', salary: '510000') 
t7.players.create(firstname: 'Marcin', lastname: 'Bulka', nationality: 'Poland', position: 'Goalkeeper', yearsofexperience: '2', salary: '250000') 
t7.players.create(firstname: 'Antonio', lastname: 'Rudiger', nationality: 'Germany', position: 'Defender', yearsofexperience: '0', salary: '100000') 
t7.players.create(firstname: 'Marcos', lastname: 'Alonso', nationality: 'Spain', position: 'Defender', yearsofexperience: '3', salary: '490000') 
t7.players.create(firstname: 'Davide', lastname: 'Zappacosta', nationality: 'Italy', position: 'Defender', yearsofexperience: '9', salary: '990000') 
t7.players.create(firstname: 'Andreas', lastname: 'Christensen', nationality: 'Denmark', position: 'Defender', yearsofexperience: '5', salary: '521000') 
t7.players.create(firstname: 'Ruben', lastname: 'Logtus-Cheek', nationality: 'England', position: 'Midfielder', yearsofexperience: '2', salary: '200000') 
t7.players.create(firstname: 'Mateo', lastname: 'Kovacic', nationality: 'Croatia', position: 'Midfielder', yearsofexperience: '2', salary: '355000') 
t7.players.create(firstname: 'George', lastname: 'McEachran', nationality: 'England', position: 'Midfielder', yearsofexperience: '1', salary: '200000') 
t7.players.create(firstname: 'Eden', lastname: 'Hazard', nationality: 'Belgium', position: 'Midfielder', yearsofexperience: '3', salary: '300000') 
t7.players.create(firstname: 'Olivier', lastname: 'Giroud', nationality: 'France', position: 'Forward', yearsofexperience: '6', salary: '620000') 
t7.players.create(firstname: 'Callum', lastname: 'Hudon-Odoi', nationality: 'England', position: 'Forward', yearsofexperience: '2', salary: '150000') 
t7.players.create(firstname: 'Pedro', lastname: 'Willian', nationality: 'Brazil', position: 'Forward', yearsofexperience: '2', salary: '210000') 
t7.players.create(firstname: 'Gonzalo', lastname: 'Higuain', nationality: 'Argentina', position: 'Forward', yearsofexperience: '7', salary: '920000') 

t8.players.create(firstname: 'Julian', lastname: 'Speroni', nationality: 'Argentina', position: 'Goalkeeper', yearsofexperience: '3', salary: '300000') 
t8.players.create(firstname: 'Wayne', lastname: 'Hennessey', nationality: 'Wales', position: 'Goalkeeper', yearsofexperience: '5', salary: '510000') 
t8.players.create(firstname: 'Vicente', lastname: 'Guaita', nationality: 'Spain', position: 'Goalkeeper', yearsofexperience: '2', salary: '250000') 
t8.players.create(firstname: 'Patrick', lastname: 'van Aanholt', nationality: 'Netherlands', position: 'Defender', yearsofexperience: '0', salary: '100000') 
t8.players.create(firstname: 'James', lastname: 'Tomkins', nationality: 'England', position: 'Defender', yearsofexperience: '3', salary: '490000') 
t8.players.create(firstname: 'Scott', lastname: 'Dann', nationality: 'England', position: 'Defender', yearsofexperience: '9', salary: '990000') 
t8.players.create(firstname: 'Mamadou', lastname: 'Sakho', nationality: 'France', position: 'Defender', yearsofexperience: '5', salary: '521000') 
t8.players.create(firstname: 'Luka', lastname: 'Milivojevis', nationality: 'Serbia', position: 'Midfielder', yearsofexperience: '2', salary: '200000') 
t8.players.create(firstname: 'Andros', lastname: 'Townsend', nationality: 'England', position: 'Midfielder', yearsofexperience: '2', salary: '355000') 
t8.players.create(firstname: 'James', lastname: 'McArthur', nationality: 'Scotland', position: 'Midfielder', yearsofexperience: '1', salary: '200000') 
t8.players.create(firstname: 'Cheikhou', lastname: 'Kouyate', nationality: 'Senegal', position: 'Midfielder', yearsofexperience: '3', salary: '300000') 
t8.players.create(firstname: 'Michy', lastname: 'Batshuayi', nationality: 'Belgium', position: 'Forward', yearsofexperience: '6', salary: '620000') 
t8.players.create(firstname: 'Jordan', lastname: 'Ayew', nationality: 'Ghana', position: 'Forward', yearsofexperience: '2', salary: '150000') 
t8.players.create(firstname: 'Connor', lastname: 'Wickham', nationality: 'England', position: 'Forward', yearsofexperience: '2', salary: '210000') 
t8.players.create(firstname: 'Christian', lastname: 'Benteke', nationality: 'Belgium', position: 'Forward', yearsofexperience: '7', salary: '920000') 

t9.players.create(firstname: 'Marcus', lastname: 'Bettinelli', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '3', salary: '300000') 
t9.players.create(firstname: 'Sergio', lastname: 'Rico', nationality: 'Spain', position: 'Goalkeeper', yearsofexperience: '5', salary: '510000') 
t9.players.create(firstname: 'Luca', lastname: 'Ashby-Hammond', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '2', salary: '250000') 
t9.players.create(firstname: 'Denis', lastname: 'Odoi', nationality: 'Belgium', position: 'Defender', yearsofexperience: '0', salary: '100000') 
t9.players.create(firstname: 'Tim', lastname: 'Ream', nationality: 'United States', position: 'Defender', yearsofexperience: '3', salary: '490000') 
t9.players.create(firstname: 'Cyrus', lastname: 'Christie', nationality: 'Ireland', position: 'Defender', yearsofexperience: '9', salary: '990000') 
t9.players.create(firstname: 'Maxime', lastname: 'Le Marchand', nationality: 'France', position: 'Defender', yearsofexperience: '5', salary: '521000') 
t9.players.create(firstname: 'Ryan', lastname: 'Sessegnon', nationality: 'England', position: 'Midfielder', yearsofexperience: '2', salary: '200000') 
t9.players.create(firstname: 'Kevin', lastname: 'McDonald', nationality: 'Scotland', position: 'Midfielder', yearsofexperience: '2', salary: '355000') 
t9.players.create(firstname: 'Neeskens', lastname: 'Kabano', nationality: 'The Democratic Repulic of Congo', position: 'Midfielder', yearsofexperience: '1', salary: '200000') 
t9.players.create(firstname: 'Tom', lastname: 'Cairney', nationality: 'Scotland', position: 'Midfielder', yearsofexperience: '3', salary: '300000') 
t9.players.create(firstname: 'Floyd', lastname: 'Ayite', nationality: 'Togo', position: 'Forward', yearsofexperience: '6', salary: '620000') 
t9.players.create(firstname: 'Aleksandar', lastname: 'Mitrovic', nationality: 'Serbia', position: 'Forward', yearsofexperience: '2', salary: '150000') 
t9.players.create(firstname: 'Luciano', lastname: 'Vietto', nationality: 'Argentina', position: 'Forward', yearsofexperience: '2', salary: '210000') 

#	HUD
t10.players.create(firstname: 'Jonas', lastname: 'Lossi', nationality: 'Denmark', position: 'Goalkeeper', yearsofexperience: '2', salary: '550000') 
t10.players.create(firstname: 'Ben', lastname: 'Hamer', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '2', salary: '450000') 
t10.players.create(firstname: 'Joel', lastname: 'Coleman', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '5', salary: '350000') 
t10.players.create(firstname: 'Tommy', lastname: 'Smith', nationality: 'England', position: 'Defender', yearsofexperience: '10', salary: '300000') 
t10.players.create(firstname: 'Chris', lastname: 'Lowe', nationality: 'Germany', position: 'Defender', yearsofexperience: '23', salary: '300000') 
t10.players.create(firstname: 'Christopher', lastname: 'Schindler', nationality: 'Germany', position: 'Defender', yearsofexperience: '2', salary: '600000') 
t10.players.create(firstname: 'Aaron', lastname: 'Mooy', nationality: 'Australia', position: 'Midfielder', yearsofexperience: '1', salary: '300000') 
t10.players.create(firstname: 'Abdelhamid', lastname: 'Sabiri', nationality: 'Germany', position: 'Midfielder', yearsofexperience: '2', salary: '890000') 
t10.players.create(firstname: 'Adama', lastname: 'Diakhaby', nationality: 'France', position: 'Forward', yearsofexperience: '2', salary: '300000') 
t10.players.create(firstname: 'Karlan', lastname: 'Grant', nationality: 'England', position: 'Forward', yearsofexperience: '2', salary: '300000') 
t10.players.create(firstname: 'Laurent', lastname: 'Depoitre', nationality: 'Belgium', position: 'Forward', yearsofexperience: '2', salary: '560000') 

#	LEI
t11.players.create(firstname: 'Kasper', lastname: 'Schmeichel', nationality: 'Denmark', position: 'Goalkeeper', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Eldin', lastname: 'Jakupovic', nationality: 'Switzerland', position: 'Goalkeeper', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Danny', lastname: 'Simpson', nationality: 'England', position: 'Defender', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Ben', lastname: 'Chilwell', nationality: 'England', position: 'Defender', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Wes', lastname: 'Morgan', nationality: 'Jamaica', position: 'Defender', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Demarai', lastname: 'Gray', nationality: 'England', position: 'Midfielder', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Marc', lastname: 'Albrighton', nationality: 'England', position: 'Midfielder', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Daniel', lastname: 'Amartey', nationality: 'Ghana', position: 'Midfielder', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Matty', lastname: 'James', nationality: 'England', position: 'Midfielder', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Youri', lastname: 'Tielemans', nationality: 'Belgium', position: 'Midfielder', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Kelechi', lastname: 'Iheanacho', nationality: 'Nigeria', position: 'Forward', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Jamie', lastname: 'Vardy', nationality: 'England', position: 'Forward', yearsofexperience: '5', salary: '560000')
t11.players.create(firstname: 'Shinji', lastname: 'Okazaki', nationality: 'Japan', position: 'Forward', yearsofexperience: '5', salary: '100000')

#	LIV
t12.players.create(firstname: 'Simon', lastname: 'Mignolet', nationality: 'Belgium', position: 'Goalkeeper', yearsofexperience: '27', salary: '100000') 
t12.players.create(firstname: 'Caoimhin', lastname: 'Kelleher', nationality: 'Ireland', position: 'Goalkeeper', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Virgil', lastname: 'van Dijk', nationality: 'Netherlands', position: 'Defender', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Dejan', lastname: 'Louvren', nationality: 'Croatia', position: 'Defender', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Joseph', lastname: 'Gomez', nationality: 'England', position: 'Defender', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Georginio', lastname: 'Wijanaldum', nationality: 'Netherlands', position: 'Midfielder', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Adam', lastname: 'Lallana', nationality: 'England', position: 'Midfielder', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Jordan', lastname: 'Henderson', nationality: 'England', position: 'Midfielder', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'James', lastname: 'Milner', nationality: 'England', position: 'Midfielder', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Curtis', lastname: 'Jones', nationality: 'England', position: 'Midfielder', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Divock', lastname: 'Origi', nationality: 'Belgium', position: 'Forward', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Daniel', lastname: 'Sturridge', nationality: 'England', position: 'Forward', yearsofexperience: '27', salary: '100000')
t12.players.create(firstname: 'Rhian', lastname: 'Brewster', nationality: 'England', position: 'Forward', yearsofexperience: '27', salary: '100000')

#	MCI
t13.players.create(firstname: 'Claudio', lastname: 'Bravo', nationality: 'Chile', position: 'Goalkeeper', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Ederson', lastname: 'Grimshaw', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Kyle', lastname: 'Walker', nationality: 'England', position: 'Defender', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Vincent', lastname: 'Kompany', nationality: 'Belgium', position: 'Defender', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'John', lastname: 'Stones', nationality: 'England', position: 'Defender', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Phil', lastname: 'Foden', nationality: 'England', position: 'Midfielder', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Riyad', lastname: 'Mahrez', nationality: 'Algeria', position: 'Midfielder', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Felix', lastname: 'Nmecha', nationality: 'England', position: 'Midfielder', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Gabriel', lastname: 'Jesus', nationality: 'Brazil', position: 'Forward', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Sergio', lastname: 'Aguero', nationality: 'Argentina', position: 'Forward', yearsofexperience: '8', salary: '100000') 
t13.players.create(firstname: 'Leroy', lastname: 'Sane', nationality: 'Germany', position: 'Forward', yearsofexperience: '8', salary: '100000') 

#	MUN
t14.players.create(firstname: 'Sergio', lastname: 'Romero', nationality: 'Argentina', position: 'Goalkeeper', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Lee', lastname: 'Grant', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Phil', lastname: 'Jones', nationality: 'England', position: 'Defender', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Luke', lastname: 'Shaw', nationality: 'England', position: 'Defender', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Eric', lastname: 'Baily', nationality: 'Cote Dlvoire', position: 'Defender', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Jesse', lastname: 'Lingard', nationality: 'England', position: 'Midfielder', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Ander', lastname: 'Herrera', nationality: 'Spain', position: 'Midfielder', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Scott', lastname: 'McTominay', nationality: 'Scotland', position: 'Midfielder', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Marcus', lastname: 'Rashford', nationality: 'England', position: 'Forward', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Joshua', lastname: 'Bohui', nationality: 'England', position: 'Forward', yearsofexperience: '18', salary: '100000') 
t14.players.create(firstname: 'Wayne', lastname: 'Rooney', nationality: 'England', position: 'Forward', yearsofexperience: '18', salary: '100000') 

#	NEW
t15.players.create(firstname: 'Robert', lastname: 'Elliot', nationality: 'Ireland', position: 'Goalkeeper', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Martin', lastname: 'Dubravka', nationality: 'Slovakia', position: 'Goalkeeper', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Calaran', lastname: 'Clark', nationality: 'Ireland', position: 'Defender', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Paul', lastname: 'Dummett', nationality: 'Wales', position: 'Defender', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Jamaal', lastname: 'Lascelles', nationality: 'England', position: 'Defender', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Christian', lastname: 'Atsu', nationality: 'Ghana', position: 'Midfielder', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Isaac', lastname: 'Hayden', nationality: 'England', position: 'Midfielder', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Matt', lastname: 'Ritchie', nationality: 'Scotland', position: 'Midfielder', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Yoshinori', lastname: 'Muto', nationality: 'Japan', position: 'Forward', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Salomon', lastname: 'Rondon', nationality: 'Venezuela', position: 'Forward', yearsofexperience: '27', salary: '100000') 
t15.players.create(firstname: 'Alan', lastname: 'Shearer', nationality: 'England', position: 'Forward', yearsofexperience: '27', salary: '100000') 

#	SOU
t16.players.create(firstname: 'Alex', lastname: 'McCarthy', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Fraser', lastname: 'Forster', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Ryan', lastname: 'Bertrand', nationality: 'England', position: 'Defender', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Jan', lastname: 'Bednarek', nationality: 'Poland', position: 'Defender', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Alfie', lastname: 'Jones', nationality: 'England', position: 'Defender', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Stuart', lastname: 'Armstrong', nationality: 'Scotland', position: 'Midfielder', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Nathan', lastname: 'Redmond', nationality: 'England', position: 'Midfielder', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Callum', lastname: 'Slattery', nationality: 'England', position: 'Midfielder', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Danny', lastname: 'Ings', nationality: 'England', position: 'Forward', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Charlie', lastname: 'Austin', nationality: 'England', position: 'Forward', yearsofexperience: '27', salary: '100000') 
t16.players.create(firstname: 'Michael', lastname: 'Obafemi', nationality: 'Ireland', position: 'Forward', yearsofexperience: '27', salary: '100000') 

#	TOT
t17.players.create(firstname: 'Hugo', lastname: 'Lloris', nationality: 'France', position: 'Goalkeeper', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Michel', lastname: 'Vorm', nationality: 'Netherlands', position: 'Goalkeeper', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Toby', lastname: 'Alderweireld', nationality: 'Belgium', position: 'Defender', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Jan', lastname: 'Vertonghen', nationality: 'Belgium', position: 'Defender', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Kieran', lastname: 'Trippier', nationality: 'England', position: 'Defender', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Erik', lastname: 'Lamela', nationality: 'Argentina', position: 'Midfielder', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Eric', lastname: 'Dier', nationality: 'England', position: 'Midfielder', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Dele', lastname: 'Alli', nationality: 'England', position: 'Midfielder', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Harry', lastname: 'Kane', nationality: 'England', position: 'Forward', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Fernando', lastname: 'Llorente', nationality: 'Spain', position: 'Forward', yearsofexperience: '10', salary: '100000') 
t17.players.create(firstname: 'Vincent', lastname: 'Janssen', nationality: 'Netherlands', position: 'Forward', yearsofexperience: '10', salary: '100000') 

#	WAT
t18.players.create(firstname: 'Heurelho', lastname: 'Gomes', nationality: 'Brazil', position: 'Goalkeeper', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Pontus', lastname: 'Dahlberg', nationality: 'Sweden', position: 'Goalkeeper', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Daryl', lastname: 'Janmaat', nationality: 'Netherlands', position: 'Defender', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Miguel', lastname: 'Britos', nationality: 'Uruguay', position: 'Defender', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Sebastian', lastname: 'Prodl', nationality: 'Austria', position: 'Defender', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Tom', lastname: 'Cleverley', nationality: 'England', position: 'Midfielder', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Nathaniel', lastname: 'Chalobah', nationality: 'England', position: 'Midfielder', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Abdoulaye', lastname: 'Doucoure', nationality: 'France', position: 'Midfielder', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Andre', lastname: 'Gray', nationality: 'England', position: 'Forward', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Gerard', lastname: 'Deulofeu', nationality: 'Spain', position: 'Forward', yearsofexperience: '4', salary: '100000') 
t18.players.create(firstname: 'Troy', lastname: 'Deeney', nationality: 'England', position: 'Forward', yearsofexperience: '4', salary: '100000') 

#	WHU
t19.players.create(firstname: 'Lukasz', lastname: 'Fabianski', nationality: 'Poland', position: 'Goalkeeper', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Adrian', lastname: ' ', nationality: 'Spain', position: 'Goalkeeper', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Pablo', lastname: 'Zabaleta', nationality: 'Argentina', position: 'Defender', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Angelo', lastname: 'Ogbonna', nationality: 'Italy', position: 'Defender', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Arthur', lastname: 'Masuaku', nationality: 'The Democratic Republic of Congo', position: 'Defender', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Manuel', lastname: 'Lanzini', nationality: 'Argentina', position: 'Midfielder', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Pedro', lastname: 'Obiang', nationality: 'Equatorial Guinea', position: 'Midfielder', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Declan', lastname: 'Rice', nationality: 'England', position: 'Midfielder', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Andy', lastname: 'Carroll', nationality: 'England', position: 'Forward', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Marko', lastname: 'Arnautovic', nationality: 'Austria', position: 'Forward', yearsofexperience: '22', salary: '100000') 
t19.players.create(firstname: 'Andriy', lastname: 'Yarmolenko', nationality: 'Ukraine', position: 'Forward', yearsofexperience: '22', salary: '100000') 

#	WQL
t20.players.create(firstname: 'John', lastname: 'Ruddy', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Will', lastname: 'Norris', nationality: 'England', position: 'Goalkeeper', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Conor', lastname: 'Coady', nationality: 'England', position: 'Defender', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Willy', lastname: 'Boly', nationality: 'France', position: 'Defender', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Ruben', lastname: 'Vinagre', nationality: 'Portugal', position: 'Defender', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Ruben', lastname: 'Neves', nationality: 'Portugal', position: 'Midfielder', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Romain', lastname: 'Saiss', nationality: 'Morocco', position: 'Midfielder', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Diogo', lastname: 'Jota', nationality: 'Portugal', position: 'Midfielder', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Raul', lastname: 'Jimenez', nationality: 'Mexico', position: 'Forward', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Ivan', lastname: 'Cavaleiro', nationality: 'Portugal', position: 'Forward', yearsofexperience: '10', salary: '100000') 
t20.players.create(firstname: 'Helder', lastname: 'Costa', nationality: 'Portugal', position: 'Forward', yearsofexperience: '10', salary: '100000') 

#   Coaches Creation
t1.coaches.create(firstname: 'Alice', lastname: 'Champ') 
t2.coaches.create(firstname: 'Kim', lastname: 'King')
t3.coaches.create(firstname: 'Place', lastname: 'Holder')
t4.coaches.create(firstname: 'Place', lastname: 'Holder')
t5.coaches.create(firstname: 'Place', lastname: 'Holder')
t6.coaches.create(firstname: 'Place', lastname: 'Holder')
t7.coaches.create(firstname: 'Place', lastname: 'Holder')
t8.coaches.create(firstname: 'Place', lastname: 'Holder')
t9.coaches.create(firstname: 'Place', lastname: 'Holder')
t10.coaches.create(firstname: 'Place', lastname: 'Holder')
t11.coaches.create(firstname: 'Place', lastname: 'Holder')
t12.coaches.create(firstname: 'Place', lastname: 'Holder')
t13.coaches.create(firstname: 'Place', lastname: 'Holder')
t14.coaches.create(firstname: 'Place', lastname: 'Holder')
t15.coaches.create(firstname: 'Place', lastname: 'Holder')
t16.coaches.create(firstname: 'Place', lastname: 'Holder')
t17.coaches.create(firstname: 'Place', lastname: 'Holder')
t18.coaches.create(firstname: 'Place', lastname: 'Holder')
t19.coaches.create(firstname: 'Place', lastname: 'Holder')
t20.coaches.create(firstname: 'Place', lastname: 'Holder')

#   Owners Creation
# Note: a team can only have one owner. 
# Because of the "has_one" relationship, owners are created using 
# the slightly different format demonstrated below
t1.owner = Owner.create(firstname: 'Taksin', lastname: 'Mann') 
t2.owner = Owner.create(firstname: 'Jane', lastname: 'Smith') 
t3.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t4.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t5.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t6.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t7.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t8.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t9.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t10.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t11.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t12.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t13.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t14.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t15.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t16.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t17.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t18.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t19.owner = Owner.create(firstname: 'Place', lastname: 'Holder')
t20.owner = Owner.create(firstname: 'Place', lastname: 'Holder')

#   Managers Creation
t1.managers.create(firstname: 'Jonathan', lastname: 'Crosby') 
t2.managers.create(firstname: 'Fred', lastname: 'Williams') 
t3.managers.create(firstname: 'Eddie', lastname: 'Howe')
t4.managers.create(firstname: 'Place', lastname: 'Holder')
t5.managers.create(firstname: 'Place', lastname: 'Holder')
t6.managers.create(firstname: 'Place', lastname: 'Holder')
t7.managers.create(firstname: 'Place', lastname: 'Holder')
t8.managers.create(firstname: 'Place', lastname: 'Holder')
t9.managers.create(firstname: 'Place', lastname: 'Holder')
t10.managers.create(firstname: 'Place', lastname: 'Holder')
t11.managers.create(firstname: 'Place', lastname: 'Holder')
t12.managers.create(firstname: 'Place', lastname: 'Holder')
t13.managers.create(firstname: 'Place', lastname: 'Holder')
t14.managers.create(firstname: 'Place', lastname: 'Holder')
t15.managers.create(firstname: 'Place', lastname: 'Holder')
t16.managers.create(firstname: 'Place', lastname: 'Holder')
t17.managers.create(firstname: 'Place', lastname: 'Holder')
t18.managers.create(firstname: 'Place', lastname: 'Holder')
t19.managers.create(firstname: 'Place', lastname: 'Holder')
t20.managers.create(firstname: 'Place', lastname: 'Holder')

#   Games creation 
# Note: this is a many to many relationship
Game.create([
	{awayteamscore: 2, hometeamscore: 1, gamedate: '05-12-2018', hometeam_id: t1.id, awayteam_id: t2.id, winningteam_id: t2.id},
	{awayteamscore: 3, hometeamscore: 3, gamedate: '06-01-2018', hometeam_id: t1.id, awayteam_id: t6.id, winningteam_id: nil}, # tie game so no winning team
	{awayteamscore: 1, hometeamscore: 0, gamedate: '06-01-2018', hometeam_id: t1.id, awayteam_id: t7.id, winningteam_id: t4.id} 
]) # DON'T FORGET: add commas between each game entry. last one doesn't need it

#   Articles creation 
a1 = t1.articles.create(title: 'Arsenal loses to Everton', articletext: 'On May 12, 2018, Arsenal lost 2-1 to Everton', timeposted: '2019-03-25 06:59:00') 
a2 = t2.articles.create(title: 'Everton wins against Arsenal', articletext: 'On May 12, 2018, Even won 2-1 to Arsenal', timeposted: '2019-03-25 06:59:00')

#   User creation
u1 = AppUser.create! :email => 'admin@1.com', :password => '123456', :password_confirmation => '123456', :admin => true
u2 = AppUser.create! :email => 'john@2.com', :password => '123456', :password_confirmation => '123456', :admin => false
u3 = AppUser.create! :email => 'sarah@2.com', :password => '123456', :password_confirmation => '123456', :admin => false

#   Comment creation 
# Note: this is a many to many relationship
Comment.create([
	{body: 'Go Arsenal!', article_id: t2.id, app_user_id: u2.id},
	{body: 'So sad :\'(', article_id: t2.id, app_user_id: u3.id},
	{body: 'Go Everton!', article_id: t1.id, app_user_id: u3.id},
	{body: 'So sad :\'(', article_id: t1.id, app_user_id: u2.id}
]) # DON'T FORGET: add commas between each game entry. last one doesn't need it


